before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
language: ruby
rvm:
  - 2.2.0
before_script:
 - "cp config/database.travis.yml config/database.yml"
 - "cp config/application.example.yml config/application.yml"
 - "RAILS_ENV=test bundle exec rake db:setup --trace"
script: RAILS_ENV=test DISPLAY=:99.0 bundle exec rspec
notifications:
  recipients:
    - coorasse@gmail.com
