ADMIN_EMAIL: ""
ADMIN_PASSWORD: ""

AWS_BUCKET: ''
AWS_ACCESS_KEY_ID: ''
AWS_SECRET_ACCESS_KEY: ''
SENTRY_DSN: ''

APP_HOST: 'localhost:3000'
APP_PORT: '3000'
MAIL_USERNAME: 'FROM MANDRILL'
MAIL_PASSWORD: 'API KEY FROM MANDRILL'
