# secrets
SECRET_KEY_BASE: 'rake secret'
DEVISE_SECRET_KEY: 'rake secret'
DEVISE_PEPPER: 'rake secret'

# admin credentials
ADMIN_EMAIL: "test@tecnologiedemocratiche.it"
ADMIN_PASSWORD: "mysuperpassword"
ADMIN_NAME: "Marco"
ADMIN_LAST_NAME: "Rossi"

# sender of emails
TD_EMAIL: 'Tecnologie Democratiche <test@tecnologiedemocratiche.it>'

S3_BUCKET_NAME: ''
AWS_ACCESS_KEY_ID: ''
AWS_SECRET_ACCESS_KEY: ''
S3_HOST_NAME: 's3-eu-central-1.amazonaws.com'

SENTRY_DSN: ''

APP_HOST: 'localhost:3000'
APP_PORT: '3000'
MAIL_USERNAME: 'FROM MANDRILL'
MAIL_PASSWORD: 'API KEY FROM MANDRILL'

PAYPAL_MERCHANT_ID: 'from paypal'

##############
#sentry settings.
#############
#SENTRY_PUBLIC_KEY: "from sentry"
#SENTRY_PRIVATE_KEY: "from sentry"
#SENTRY_PORT: "from sentry"

# new relic
#NEW_RELIC_LICENSE_KEY: 'from newrelic'
#NEW_RELIC_APP_NAME: 'Tecnologie Democratiche'

