default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: postgres

development:
  <<: *default
  database: tecnologie_democratiche_development

test:
  <<: *default
  database: tecnologie_democratiche_test

production:
  <<: *default
  database: tecnologie_democratiche_production
